### PR TITLE
Fix #25

### LINKED ISSUE #25: Should InPath('foo/bar') be satisfied by 'foo/barMOAR/some-file.txt'?
I don't think it should. I think it is a bug.

This test I added to `InPathTest.php` currently fails on master:

```php
    /**
     * @uses \Flyfinder\Path
     *
     * @covers ::__construct
     * @covers ::isSatisfiedBy
     */
    public function testNoFalsePositiveWithLongerDirName() : void
    {
        $prefixDir    = 'absolute/path';
        $absolutePath = 'absolute/pathMOAR/to/file.txt';
        $spec         = new InPath(new Path($prefixDir));
        $this->assertFalse($spec->isSatisfiedBy([
            'type' => 'file',
            'path' => $absolutePath,
            'dirname' => dirname($absolutePath),
            'filename' => 'file',
            'extension' => 'txt',
            'basename' => 'file.txt',
        ]));
    }
```

If this is indeed a bug then I have a fix. PR will follow shortly.

### PR DESCRIPTION
**Pull request by rulatir**
I believe InPath('foo/bar') should not be satisfied by 'foo/barMOAR/some-file.txt'. This fixes it.

### CODE REVIEW

**Comment by jaapio** [comment]
Thanks for your PR.

This change is possibly a breaking change, so I have to think about that. The behavior is a bit opinionated, it depends on what you would expect and how your configuration is. If you specify your path as `foo/bar/` it would work the same way as you are now implementing?

**Comment by rulatir** [comment]
My ahem... opinionated opinion is that trailing directory separator should never be meaningful. Every API that receives a path in a string should trim trailing directory separators from it before doing anything else with it.

I also think it is common sense to expect that `foo/bar` should never mean `foo/bar*`. If one **intends** `foo/bar*`, they should explicitly use either `Glob` or the limited glob capability of `InPath`. I cannot think of a situation where one would expect that `foo/barMOAR/some-file.txt` should be considered to be "in path" `foo/bar`. It is in `foo/barMOAR`, and firmly **outside** the subtree rooted at `foo/bar`.

**Comment by jaapio** [comment]
Thanks for your feedback. I think I do agree with your arguments. When we wrote the first version of this library it was not containing a glob, so `inPath` had kind of mixed behavior. Could you please add a `changelog.md` with a note to this PR in the root of the project? After that, we can merge this.

**Comment by rulatir** [comment]
OK. I'll be basing the changelog entry structure on the one in phpDocumentor.

**Pull request merged**
