### PR TITLE
Adding support for PHP 8.x

### LINKED ISSUE #38: Any chance to bump PHP req to 8.* speedily?
As per topic, can we extend the PHP requirement to 8.*?

### PR DESCRIPTION
**Pull request by douglasmiller**
An extension of @jnkowa-gfk's PR #39  which closes #38.

This extends #39 by updating the `phive.xml` file to specify newer `installed` versions and an updated gpg key for @maglnet's `ComposerRequireChecker` phar file.

### CODE REVIEW

**Comment by douglasmiller** [comment]
https://github.com/douglasmiller/FlyFinder/pull/3 is a PR against my fork showing the GitHub actions workflow running to success.

**Comment by douglasmiller** [comment]
@jaapio, any thoughts on this update to get the tests to pass?

**Comment by jaapio** [comment]
There seems to be an issue on github with the approval of the workflow. I will try to run the workflow later.

**Comment by jaapio** [comment]
PR looks good to me. Thanks

**Comment by jnkowa-gfk** [comment]
@douglasmiller  thanks for the work and the fix.
appreciated very much.

**Pull request merged**
