### PR TITLE
Upgrade tools to fix installation

### PR DESCRIPTION
**Pull request by villfa**
Hi,

I got this error message while trying to install the tools with Phive:
```sh
# phive install
Phive 0.14.4 - Copyright (C) 2015-2022 by Arne Blankerts, Sebastian Heuer and Contributors
Downloading https://phar.phpunit.de/phpunit-8.5.15.phar
Downloading https://phar.phpunit.de/phpunit-8.5.15.phar.asc
Copying phpunit-8.5.15.phar to FlyFinder/tools/phpunit
[ERROR]    No matching release found!
```

The installation works after upgrading them, but I had to also update their configuration to make them pass.

### CODE REVIEW

**Comment by jaapio** [comment]
Hi,

Thanks for your contribution! I enabled the pipelines for your contribution. 
If you have time I would be very grateful, if you are able to fix the pipeline: 
https://github.com/phpDocumentor/FlyFinder/blob/master/.github/workflows/push.yml#L43 contains a list of accepted gpg keys. The build is failing because the psalm key is changed.

**Comment by villfa** [comment]
The GPG keys are now up to date.

I've also made other modifications:
- remove `pecl` from `shivammathur/setup-php` since this attribute doesn't exist anymore
- remove xdebug when not necessary
- run the version of PHPStan downloaded by Phive

On my fork I have errors from phpcs but I don't know how you would like to solve that. By applying the suggestions, or by disabling the rules producing those errors.

**Comment by jaapio** [comment]
Let's do this in steps, I can live with cs errors for now if we are fixing the rest of the pipeline :+1:

**Comment by jaapio** [comment]
Your changes are working. The pipeline is working again thank you so much for helping me out. 

I will merge this pr. in a sec. 
If you want to provide a pr with the cs changes applied that would be awesome. But I do understand that you when other things to do.

**Pull request merged**
